/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountSummary: typeof import('./components/dashboard/AccountSummary.vue')['default']
    CapitalLogList: typeof import('./components/fund/CapitalLogList.vue')['default']
    DonutChart: typeof import('./components/positions/DonutChart.vue')['default']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    FundAllocationForm: typeof import('./components/fund/FundAllocationForm.vue')['default']
    HoldingCard: typeof import('./components/dashboard/HoldingCard.vue')['default']
    LoadingSkeleton: typeof import('./components/common/LoadingSkeleton.vue')['default']
    MainLayout: typeof import('./components/common/MainLayout.vue')['default']
    PoolPositionCard: typeof import('./components/positions/PoolPositionCard.vue')['default']
    PoolSelector: typeof import('./components/common/PoolSelector.vue')['default']
    ProfitCard: typeof import('./components/dashboard/ProfitCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StockSearch: typeof import('./components/trade/StockSearch.vue')['default']
    TradeForm: typeof import('./components/trade/TradeForm.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VerificationCard: typeof import('./components/trade/VerificationCard.vue')['default']
  }
}
